version: '3.2'

services:
  metrics_app:
    image: dash39/metrics_app
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: metrics_app

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/config/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: $PWD/config
        target: /etc/config
    restart: unless-stopped
    container_name: prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: grafana
