scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metrics-app'
    scrape_interval: 1s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']